# Generated by Django 5.0.3 on 2024-06-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_remove_userprofile_name_userprofile_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='passport_pic',
            field=models.FileField(blank=True, null=True, upload_to='user'),
        ),
    ]
