# Generated by Django 5.0.3 on 2024-06-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_userprofile_passport_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='s3_object_key_id',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
