# Generated by Django 5.0.3 on 2024-06-16 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_userprofile_s3_object_key_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='passport_pic',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='s3_object_key_id',
        ),
    ]
